# Generated by Django 3.1.5 on 2021-01-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stcok',
            name='key',
        ),
        migrations.RemoveField(
            model_name='stcok',
            name='name',
        ),
        migrations.AddField(
            model_name='stcok',
            name='company',
            field=models.CharField(default='Other company', max_length=50, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='stcok',
            name='symbol',
            field=models.CharField(default='', max_length=50, verbose_name='Symbol'),
        ),
    ]
