# Generated by Django 3.1.5 on 2021-01-31 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210129_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stcok',
            new_name='Stock',
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='time_symbol')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
            ],
        ),
    ]
