# Generated by Django 3.1.5 on 2021-02-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210131_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='adj_close_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Adj Close'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='close_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Close'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='date',
            field=models.DateTimeField(default=None, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='high_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='High'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='low_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Low'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='open_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Open'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='timestamp_symbol'),
        ),
    ]
