# Generated by Django 3.1.5 on 2021-02-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210201_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_set', to='app.stock'),
        ),
        migrations.CreateModel(
            name='PredictPrice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='timestamp_symbol')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Price')),
                ('date', models.DateTimeField(default=None, verbose_name='Date')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_set', to='app.stock')),
            ],
        ),
    ]
