# Generated by Django 3.1.5 on 2021-03-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210223_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictprice',
            name='model_type',
            field=models.CharField(default=None, max_length=20, verbose_name='model_type'),
        ),
    ]
